### ISSUE TITLE
About videotransformer.py

### ISSUE THREAD

**Issue by q104769424** [sohailahmedkhan/Video_Transformer_Deepfake_Detector#1]
Hi, I am interested in your code, then I found the videotransformer.py has some bugs, like x = self.linear_3(x) and no variable is self.linear_3,  and no function named reduce, can your share the final code about videotransformer.py, my email is q104769424@gmail.com, thanks.

**Comment by sohailahmedkhan** [comment]
Hi,

I have updated the video transformer code. You can check now. If you still face any issues, please let me know.

**Comment by q104769424** [comment]
Thanks, I try it.👍

Sohail Ahmed Khan ***@***.***>於 2022年5月17日 週二，上午12:31寫道：

**Comment by q104769424** [comment]
Hi,
I face the issue in videotransformer.py, in line 235:
if hasattr(self, 'class_token'):
        x = torch.cat((self.class_token.expand(batch, -1, -1), x), dim=1)
But input shape is 5 dim(batch, num_images, channels, height, width), then self.class_token has 3 dim, they do not match, how can I modify it.

**Comment by sohailahmedkhan** [comment]
It should work now. Please check.

**Comment by q104769424** [comment]
Hi, 
When I use videotransformer.py like:
model = VideoTransformer('B_16_imagenet1k', pretrained=True, image_size = 384, num_classes = 2, seq_embed=True, hybrid=False, device='cuda')
Input shape is (1, 9,3,384,384) , 
the error can find in image_features = linear_3(image_features) of DDFA.py,
error message is RuntimeError: mat1 and mat2 shapes cannot be multiplied (768x456 and 252x32).
How can I modify it?

**Comment by sohailahmedkhan** [comment]
Hi, until now only Hybrid video transformer is working. I will try to fix the error this week.

Until then, you can set "hybrid=True", and it will work.

**Comment by q104769424** [comment]
Hi, when I set hybrid=True, the error message is RuntimeError: mat1 and mat2 shapes cannot be multiplied (768x144 and 100x32), 
the error is image_features = linear_1(image_features) in DDFA.py,  have I missed something?

**Comment by sohailahmedkhan** [comment]
Hi, it works for me. I don't know what is the problem at your side. Please delete and clone the repository again. It should work.

**Comment by q104769424** [comment]
Hi, Can you share the model weight?

**Comment by zhouk369** [comment]
Hi, I am interested in your paper, can you share the loss function of incremental learning mentioned in your paper?

**Comment by sohailahmedkhan** [comment]
> Hi, I am interested in your paper, can you share the loss function of incremental learning mentioned in your paper?

Hi, thanks for your interest in this research. We do not use a separate loss function to incrementally train our models. We just use the same binary cross entropy loss function to train the models on new datasets. However, (1) we decrease the learning rate when we train on new datasets, and (2) we use a very small number of training samples while training on new datasets.

**Comment by zhouk369** [comment]
> > Hi, I am interested in your paper, can you share the loss function of incremental learning mentioned in your paper?
> 
> Hi, thanks for your interest in this research. We do not use a separate loss function to incrementally train our models. We just use the same binary cross entropy loss function to train the models on new datasets. However, (1) we decrease the learning rate when we train on new datasets, and (2) we use a very small number of training samples while training on new datasets.

Thank you for your answer. At the same time, I still have some questions. Is the loss function you mentioned composed of two parts? And are these two functions cross-entropy loss functions? In addition, are a very small number of training samples from a new dataset or from an old dataset?

**Comment by sohailahmedkhan** [comment]
Hi, 

We only use one loss function, which is the cross-entropy loss. For incremental learning, we load the pretrained model which we have already trained on a big deepfake detection dataset, and then fine-tune it on a new, small deepfake dataset. 

For example, we first trained our model on FaceForensics++ dataset. As an example, consider that we train it using 200k images from the FaceForensics++ dataset using cross-entropy loss function. After training, we save the model weights. 

For incremental learning, we then load these saved weights and train the model on DFDC dataset, by using only around 10 to 15k images, and using the same loss function, but this time we use a very small learning rate. 

I hope you get the point now.

**Comment by zhouk369** [comment]
> Hi

Thanks for your detailed answers. However, from your answers, the incremental training is just a basic fine-tuning process with a subset dataset and a small learning rate. Could you tell me what do you do specifically to prevent catastrophic forgetting? From your paper, I think the first item of loss function is used to prevent forgetting but your previous answers tell me otherwise.
Thanks again for keeping answer all my questions. Your work is so brilliant and it’s performance is really good. Therefore, I do want to figure out how that happened.

**Comment by sohailahmedkhan** [comment]
Hi, yes you are right that we only do basic fine-tuning to achieve incremental learning in our approach. We experimented with different architectural settings, hyperparameters and different types of input data. Because of the architectural design of our model, and because we trained it with multimodal data, we think that is the reason why our model achieves incremental learning. 

We confirmed this hypothesis by training different variants of our models on different types on input data, for example, we trained a our hybrid model using only face cropped images incrementally, and found that it does forgets what it had learnt before. However, when we tested the same hybrid transformer model along with segment embeddings and multimodal data, we found that it does not catastrophically forgets what it had learnt earlier, as can be seen in the results presented in the paper.

All in all, we think that the model achieves incremental learning because of its unique architectural design, as well as by being trained on multimodal data.
